### PR TITLE
scss sprite sizes #37

### PR DESCRIPTION
**Pull request by galymax**
Ok, I added sprite sizes for scss. Unfortunately I'm not familiar with less.

### CODE REVIEW

**Comment by cascornelissen** [comment]
Looks good, I'll merge it when I have the time to release a new version 👍

**Comment by galymax** [comment]
Thank you.

**Comment by cascornelissen** [comment]
Hi @galymax, thanks once more for the PR. 

Since a lot has changed since the creation of this PR and there were a few conflicts I've decided to reimplement your setup on the latest changes in commit 3e252cb. I've also mentioned you in the release notes of version [`2.7.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v2.7.0) which includes this feature.

**Comment by galymax** [comment]
Cool, thanks a lot.

**Pull request closed without merging**
