### PR TITLE
Adds preserveAspectRatio attribute if available

### PR DESCRIPTION
**Pull request by arti5m**

### CODE REVIEW

**Comment by cascornelissen** [comment]
I don't think this is something the `svg-spritemap-webpack-plugin` should handle. I suppose the attribute gets stripped by SVGO? Could you confirm this by setting the [`output.svgo`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#outputsvgo--true) option to `false`? If that leaves the `preserveAspectRatio` in place, you might want to look into disabling the [`removeUnknownsAndDefaults`](https://github.com/svg/svgo/blob/master/plugins/removeUnknownsAndDefaults.js) or [`removeEmptyAttrs`](https://github.com/svg/svgo/blob/master/plugins/removeEmptyAttrs.js) SVGO plugins.

**Comment by cascornelissen** [comment]
Ping @arti5m, any opinions on this?

**Comment by arti5m** [comment]
@cascornelissen Disabling SVGO plugins was the first thing I tried. No luck there, sadly.

**Comment by cascornelissen** [comment]
@arti5m, I just finished digging into this, seems like it's a combination of the SVGO setup and the fact that it's an attribute on the root SVG element. 

I would like to make the setup a little more variable (make it support pretty much any attribute except a couple like `viewBox` and `height`/`width` because we add/remove these on purpose) and add them to the correct elements as well (e.g. [`preserveAspectRatio`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/view#Specific_attributes) is also supported on `<view>` elements).

I've made the required changes in commit 380f423, which is currently in [`master`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/commits/master), based on the PR you've submitted, so thanks for that! 

I feel like this should solve your use-case among others (e.g. #40). Are you able to check it out and confirm it works correctly? You're, of course, free to submit additional changes for this feature (in this PR as well). Installing the `master` branch directly can be done like this:

```
npm install cascornelissen/svg-spritemap-webpack-plugin#master
```

Let me know! ✌️

**Comment by arti5m** [comment]
@cascornelissen 
I was not able to get this to work (even with SVGO disabled). It's still stripping the attribute.

I expect to be able to add the `preserveAspectRatio` attribute to the `<svg>` element of a source svg file and see a sprite like the following come out the other side:
```
<svg xmlns="http://www.w3.org/2000/svg">
  ...
  <symbol id="full-logo" viewBox="0 0 205 107" preserveAspectRatio="xMinYMax">
    <g fill="currentColor" fill-rule="evenodd"> ... 
  </symbol>
  ...
</svg>
```

**Comment by arti5m** [comment]
Spoke too soon. It works!!
🎉 🎉 🎉

**Comment by cascornelissen** [comment]
@arti5m, this fix has been released in version [`3.1.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v3.1.0) 🚀

**Pull request closed without merging**
